Num2/urls.py
from django.contrib import admin  
from django.urls import path  
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('addnew',views.addnew),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
    path('indexEnter/', views.indexEnter),
    path('addnewEnter',views.addnewEnter),
    path('editEnter/<int:id>', views.editEnter),
    path('updateEnter/<int:id>', views.updateEnter),
    path('deleteEnter/<int:id>', views.destroyEnter),
    path('indexSuivi/', views.indexSuivi)
]

myapp/models.py
from django.db import models
from django.contrib import admin

# Create your models here.

class Employee(models.Model):  
    name = models.CharField(max_length=100)  
    email = models.EmailField()  
    contact = models.CharField(max_length=15) 
  
    class Meta:  
        db_table = "employee"

class Entreprises(models.Model):
    nameEnterprise = models.CharField(max_length=100)
    Email = models.EmailField()
    typeEntreprise = models.CharField(max_length=50)

    class Meta:
        db_table = "entreprises" 

class SuiviContrat(models.Model):
    dateDebut = models.DateField()
    dateFin = models.DateField()
    Poste = models.CharField(max_length=50, default="Développeur")
    EmployeeName = models.ForeignKey(Employee, on_delete=models.CASCADE)
    NewContrat = models.ForeignKey(Entreprises, on_delete=models.CASCADE)

    class Meta:
        db_table = "suivi_contrat"

myapp/forms.py
from django import forms  
from myapp.models import Employee, Entreprises, SuiviContrat

class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = ['name', 'contact', 'email']
        widgets = { 'name': forms.TextInput(attrs={ 'class': 'form-control' }), 
            'email': forms.EmailInput(attrs={ 'class': 'form-control' }),
            'contact': forms.TextInput(attrs={ 'class': 'form-control' }),
            }

class EntreprisesForm(forms.ModelForm):  
    class Meta:
        model = Entreprises  
        fields = ['nameEnterprise', 'typeEntreprise', 'Email']
        widgets = { 'nameEnterprise': forms.TextInput(attrs={ 'class': 'form-control' }), 
            'Email': forms.EmailInput(attrs={ 'class': 'form-control' }),
            'typeEntreprise': forms.TextInput(attrs={ 'class': 'form-control' }),
            }

class SuiviContratForm(forms.ModelForm):  
    class Meta:  
        model = SuiviContrat  
        fields = ['dateDebut', 'dateFin','EmployeeName', 'NewContrat']
        widgets = { 
            'dateDebut': forms.DateInput(attrs={ 'class': 'form-control' }), 
            'dateFin': forms.DateInput(attrs={ 'class': 'form-control' }),
            #'EmployeeName': forms.IntegerField(attrs={ 'class': 'form-control' }),
            #'NewContrat': forms.IntegerField(attrs={ 'class': 'form-control' })
        }

myapp/views.py
from django.shortcuts import render, redirect  
from myapp.forms import EmployeeForm,EntreprisesForm,SuiviContratForm
from myapp.models import Employee, SuiviContrat,Entreprises

# Create your views here.

def addnew(request):  
    if request.method == "POST":  
        form = EmployeeForm(request.POST)  
        if form.is_valid():  
            try:
                form.save()  
                return redirect('/')  
            except:  
                pass 
    else:  
        form = EmployeeForm()
    suivicontrats = SuiviContrat.objects.all()
    return render(request,'index.html',{'form':form, 'suivicontrats': suivicontrats}) 

def index(request):
    employees = Employee.objects.all()
    suivicontrats = SuiviContrat.objects.all()
    return render(request,"show.html",{'employees':employees, 'suivicontrats': suivicontrats})

def indexSuivi(request):
    suivicontrats = SuiviContrat.objects.all()
    return render (request,"showSuivi.html",{'suivicontrats': suivicontrats})

def edit(request, id):  
    employee = Employee.objects.get(id=id)  
    return render(request,'edit.html', {'employee':employee}) 

def update(request, id):  
    employee = Employee.objects.get(id=id)  
    form = EmployeeForm(request.POST, instance = employee)  
    if form.is_valid():  
        form.save()
        return redirect("/")  
    return render(request, 'edit.html', {'employee': employee})

def destroy(request, id):  
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect("/")

def addnewEnter(request):  
    if request.method == "POST":  
        form = EntreprisesForm(request.POST)  
        if form.is_valid():  
            try:
                form.save()  
                return redirect("/indexEnter")  
            except:  
                pass 
    else:  
        form = EntreprisesForm()
    return render(request,'indexEnter.html',{'form':form})

def indexEnter(request):  
    enterprises = Entreprises.objects.all()
    return render(request,"showEnter.html",{'enterprises':enterprises})

def editEnter(request, id):  
    enterprise = Entreprises.objects.get(id=id)  
    return render(request,'editEnter.html', {'enterprise':enterprise})

def updateEnter(request, id):  
    enterprise = Entreprises.objects.get(id=id)  
    form = EntreprisesForm(request.POST, instance = enterprise)  
    if form.is_valid():  
        form.save()  
        return redirect("/indexEnter")
    return render(request, 'editEnter.html', {'enterprise': enterprise})

def destroyEnter(request, id):  
    enterprise = Entreprises.objects.get(id=id)
    enterprise.delete()
    return redirect("/indexEnter")

templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

</head>

<body>
  <!-- begin -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Gestionnaires</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/">Employés</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/indexEnter">Entreprises</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Voir plus
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="/indexEnter">Suivi</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>
  <!-- end -->
  <div class="container">
    <div class="row">
      {% block content %}{% endblock %}
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
  </script>
  <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>

  <script>
    $(document).ready(function () {
      $('#bootstrapdatatable').DataTable({
        "aLengthMenu": [
          [3, 5, 10, 25, -1],
          [3, 5, 10, 25, "All"]
        ],
        "iDisplayLength": 3
      });
    });
  </script>
</body>

</html>

templates/edit.html
{% extends "base.html" %}

{% block title %}Ajouts de nouveaux enregistrements d'employé{% endblock title %}

{% block content %}
<div class="col-md-12">
  <form method="POST" class="post-form" action="/update/{{employee.id}}">
    {% csrf_token %}
    <div class="container">
      <br>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <h3>Mettre à jour les détails</h3>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Id:</label>
        <div class="col-sm-4">
          <input type="text" class="form-control" name="id" id="id_id" required maxlength="20"
            value="{{ employee.id }}" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Name:</label>
        <div class="col-sm-4">
          <input type="text" class="form-control" name="name" id="id_name" required maxlength="100"
            value="{{ employee.name }}" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Email:</label>
        <div class="col-sm-4">
          <input type="email" class="form-control" name="email" id="id_email" required maxlength="254"
            value="{{ employee.email }}" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Contact:</label>
        <div class="col-sm-4">
          <input type="text" class="form-control" name="contact" id="id_contact" required maxlength="15"
            value="{{ employee.contact }}" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <button type="submit" class="btn btn-success btn-lg">Mettre à jour</button>
        </div>
      </div>
    </div>
  </form>
  {% endblock content %}

templates/editEnter.html
{% extends "base.html" %}

{% block title %}Ajouts de nouveaux enregistrements d'employé{% endblock title %}

{% block content %}
<div class="col-md-12">
  <form method="POST" class="post-form" action="/updateEnter/{{enterprise.id}}">
    {% csrf_token %}
    <div class="container">
      <br>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <h3>Mettre à jour les détails</h3>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Id:</label>
        <div class="col-sm-4">
          <input type="text" class="form-control" name="id" id="id_id" required maxlength="20"
            value="{{ enterprise.id }}" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Nom enterprise:</label>
        <div class="col-sm-4">
          <input type="text" class="form-control" name="nameEnterprise" id="id_nameEnterprise" required maxlength="100"
            value="{{ enterprise.nameEnterprise }}" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Email:</label>
        <div class="col-sm-4">
          <input type="email" class="form-control" name="Email" id="id_Email" required maxlength="254"
            value="{{ enterprise.Email }}" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Type enterprise:</label>
        <div class="col-sm-4">
          <input type="text" class="form-control" name="typeEntreprise" id="id_typeEntreprise" required maxlength="50"
            value="{{ enterprise.typeEntreprise }}" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <button type="submit" class="btn btn-success btn-lg">Mettre à jour</button>
        </div>
      </div>
    </div>
  </form>
  {% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block title %}Ajouts de nouveaux enregistrements d'employé{% endblock title %}

{% block content %}
<div class="col-md-12">
  <form method="POST" class="post-form" action="/addnew">
    {% csrf_token %}
    <div class="container">
      <br>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <h3>Entrez les détails</h3><br />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Name:</label>
        <div class="col-sm-4">
          {{ form.name }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Email:</label>
        <div class="col-sm-4">
          {{ form.email }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Contact:</label>
        <div class="col-sm-4">
          {{ form.contact }}
        </div>
        <br /><br /><br />
      </div>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <button type="submit" class="btn btn-primary">Envoyer</button><br /><br />
        </div>
      </div>
    </div>
  </form>
</div>
<div class="col-md-12"></div>
<h2>Les contrats des employées</h2>
<div class="table-responsive">
  <table class="table table-striped table-bordered" width="100%"><br />
    <thead>
      <th>ID</th>
      <th>Date-debut Contrat</th>
      <th>Date-Fin Contrat</th>
      <th>Id Employer</th>
      <th>Id Contrat</th>
      <th>Poste</th>
    </thead>
    <tbody>
      {% for SuiviContrat in suivicontrats %}
      <tr>
        <td>{{ SuiviContrat.id }}</td>
        <td>{{ SuiviContrat.dateDebut }}</td>
        <td>{{ SuiviContrat.dateFin }}</td>
        <td>{{ SuiviContrat.EmployeeName.id }}</td>
        <td>{{ SuiviContrat.NewContrat.id }}</td>
        <td>{{ SuiviContrat.Poste }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
{% endblock content %}

templates/indexEnter.html
{% extends "base.html" %}

{% block title %}Ajouts de nouveaux enregistrements d'Entreprise{% endblock title %}

{% block content %}
<div class="col-md-12">
  <form method="POST" class="post-form" action="/addnewEnter">
    {% csrf_token %}
    <div class="container">
      <br>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <h3>Entrez les détails</h3><br />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Nom Entreprise:</label>
        <div class="col-sm-4">
          {{ form.nameEnterprise }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Email:</label>
        <div class="col-sm-4">
          {{ form.Email }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Type Entreprise:</label>
        <div class="col-sm-4">
          {{ form.typeEntreprise }}
        </div>
        <br /><br /><br />
      </div>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <button type="submit" class="btn btn-primary">Envoyer</button>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock content %}

templates/show.html
{% extends "base.html" %}

{% block title %}Dossiers des employés{% endblock title %}

{% block content %}
<br />
<div class="col-md-12"><span><a href="/addnew" class="btn btn-primary">Ajouts de nouveaux enregistrements</a></span>
    <div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%"><br />
            <thead>
                <th><input type="checkbox" id="checkall" /></th>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Contact</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </thead>
            <tbody>
                {% for employee in employees %}
                <tr>
                    <td><input type="checkbox" class="checkthis" /></td><br />
                    <td>{{ employee.id }}</td>
                    <td>{{ employee.name }}</td>
                    <td>{{ employee.email }}</td>
                    <td>{{ employee.contact }}</td>
                    <td>
                        <p data-placement="top" data-toggle="tooltip" title="Modifier"><a href="/edit/{{ employee.id }}"
                                class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal"
                                data-target="#edit"><span class="glyphicon glyphicon-pencil"></span></a></p>
                    </td>
                    <td>
                        <p data-placement="top" data-toggle="tooltip" title="Supprimer"><a
                                href="/delete/{{ employee.id }}"
                                onclick="return confirm('Êtes-vous sûrs de vouloir supprimer cet élément?')"
                                class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal"
                                data-target="#delete"><span class="glyphicon glyphicon-trash"></span></a></p>
                    </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
</div>
{% endblock content %}

templates/showEnter.html
{% extends "base.html" %}

{% block title %}Dossiers des Entreprises{% endblock title %}

{% block content %}
<br /><br />
<div class="col-md-12"><span><a href="/addnewEnter" class="btn btn-primary">Ajouts de nouveaux
            enregistrements</a></span>
    <div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%"><br /><br />
            <thead>
                <th><input type="checkbox" id="checkall" /></th>
                <th>ID</th>
                <th>Nom Entreprise</th>
                <th>Email</th>
                <th>Type Entreprise</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </thead>
            <tbody>
                {% for enterprise in enterprises %}
                <tr>
                    <td><input type="checkbox" class="checkthis" /></td><br />
                    <td>{{ enterprise.id }}</td>
                    <td>{{ enterprise.nameEnterprise }}</td>
                    <td>{{ enterprise.Email }}</td>
                    <td>{{ enterprise.typeEntreprise }}</td>
                    <td>
                        <p data-placement="top" data-toggle="tooltip" title="Modifier"><a
                                href="/editEnter/{{ enterprise.id }}" class="btn btn-primary btn-xs" data-title="Edit"
                                data-toggle="modal" data-target="#edit"><span
                                    class="glyphicon glyphicon-pencil"></span></a></p>
                    </td>
                    <td>
                        <p data-placement="top" data-toggle="tooltip" title="Supprimer"><a
                                href="/deleteEnter/{{ enterprise.id }}"
                                onclick="return confirm('Êtes-vous sûrs de vouloir supprimer cet élément?')"
                                class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal"
                                data-target="#delete"><span class="glyphicon glyphicon-trash"></span></a></p>
                    </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
</div>
{% endblock content %}

templates/showSuivi.html
{% extends "base.html" %}

{% block title %}Dossiers des Entreprises{% endblock title %}

{% block content %}
<br /><br />
<div class="col-md-12"><span><a href="/addnewEnter" class="btn btn-primary">Ajouts de nouveaux
      enregistrements</a></span>
  <div class="col-md-12"></div>
  <h2>Les contrats des employées</h2>
  <div class="table-responsive">
    <table class="table table-striped table-bordered" width="100%"><br />
      <thead>
        <th>ID</th>
        <th>Date-debut Contrat</th>
        <th>Date-Fin Contrat</th>
        <th>Id Employer</th>
        <th>Id Contrat</th>
        <th>Poste</th>
      </thead>
      <tbody>
        {% for SuiviContrat in suivicontrats %}
        <tr>
          <td>{{ SuiviContrat.id }}</td>
          <td>{{ SuiviContrat.dateDebut }}</td>
          <td>{{ SuiviContrat.dateFin }}</td>
          <td>{{ SuiviContrat.EmployeeName.id }}</td>
          <td>{{ SuiviContrat.NewContrat.id }}</td>
          <td>{{ SuiviContrat.Poste }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% endblock content %}

templates/test.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>



    <!-- Single button -->  
    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            Action <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
        </ul>
    </div>


    <!-- Example single danger button -->
<div class="btn-group">
    <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Action
    </button>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">Separated link</a>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>

</html>